#!/bin/bash

make

PRODUCERS_NUM=2
CONSUMERS_NUM=1
BUFFER_SIZE=100
SOURCE_FILE=arguments.txt
LENGTH=45
SEARCH_MODE=1
LOGGING_LEVEL=1
nk=0

./main $PRODUCERS_NUM $CONSUMERS_NUM $BUFFER_SIZE $SOURCE_FILE $LENGTH $SEARCH_MODE $LOGGING_LEVEL $nk >> log.txt